### ISSUE TITLE
Problem with reference in Kestrel-1.0.1

### ISSUE THREAD

**Issue by cartal** [paudano/kestrel#1]
Hi,

I have been trying to run Kestrel like this:

`java -jar -Xmx10g kestrel.jar count -f fasta -r reference.fasta -s TcI-H1 -p TcI-H1 --minsize=10 read_R1.fq.gz read_R2.fq.gz
` 

But I end up with the following error:

![screen shot 2017-08-04 at 07 17 23](https://user-images.githubusercontent.com/3297906/28956586-a750c3a2-78e5-11e7-8b45-3e3aed42aeee.png)

Any ideas of what's going on? 

I have used the previous version of Kestrel without any problems, but now I've got this error.

Thanks in advance

**Comment by paudano** [comment]
I think this command is mixing Kestrel with KAnalyze. The "count" keyword is not part of Kestrel. The error message says:

> Error loading reader for input source count

Any non-option words on the command-line are interpreted as input files, so it is trying to read an input sequence file named "count". Kestrel uses KAnalyze to read sequences, and KAnalyze attempts to use a filename pattern to load the correct reader for each file. Since it cannot match a pattern (no file extension such as ".fasta'), it returns this error. Removing the count keyword will fix this.

**Comment by cartal** [comment]
Hi,

I have tried removing the `count` option before posting the error. 

By now I have tried both, the java app and the wrapper now and the wrapper gives the same error - even when only the reference and the reads are provided - and the java app doesn't recognise the FASTA reference (given as a FASTA file with the -r option) and instead goes and tries to read the FASTQ file.

**Comment by paudano** [comment]
If the count keyword was removed, then there must be a different error message. Can you post it?

**Comment by paudano** [comment]
I assume you were able to get it running. If you are still having trouble, please feel free to re-open this case.
